# Generated by Django 4.0.3 on 2022-03-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Title of the post"),
                ),
                ("content", models.TextField(verbose_name="Content of the post")),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="Created at"),
                ),
                (
                    "cover",
                    models.ImageField(blank=True, null=True, upload_to="posts/covers/"),
                ),
            ],
            options={
                "verbose_name": "Posts",
                "verbose_name_plural": "Posts",
            },
        ),
    ]
